// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3nSzdiPLRfv51XqFgBlCXClojejptGmw',
    appId: '1:688949986759:web:f06a14af3ba86a1aa445e2',
    messagingSenderId: '688949986759',
    projectId: 'task-schedule-33122',
    authDomain: 'task-schedule-33122.firebaseapp.com',
    storageBucket: 'task-schedule-33122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0K_IO90qvG021Qf4-J-yCH4zp2RRQoQ',
    appId: '1:688949986759:android:28d8986b18a809e0a445e2',
    messagingSenderId: '688949986759',
    projectId: 'task-schedule-33122',
    storageBucket: 'task-schedule-33122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtra1bMaEwzb1E-rGAy4boIRqL45ZYmQ8',
    appId: '1:688949986759:ios:33c0fbc904614eeea445e2',
    messagingSenderId: '688949986759',
    projectId: 'task-schedule-33122',
    storageBucket: 'task-schedule-33122.firebasestorage.app',
    iosBundleId: 'com.example.collabTodo',
  );
}
